@import './js/header.js';
@import './js/hero.js';
@import './js/about.js';
@import './js/benefits.js';
@import './js/project.js';
@import './js/faq.js';
@import './js/covers.js';
@import './js/reviews.js';
@import './js/together.js';